[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/","forge-std/=lib/forge-std/src/"]
ffi = true # if set to true, allows foundry to run commands on the machine



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
